AccountsApi.Tests/V1/Controllers/AccountsApiControllerTests.cs
this is a sample to investigate the circle CI suspension!
=> Controller post unit testing / added new test fact

.circleci/config.yml, AccountsApi.Tests/V1/Domain/AccountSnsTests.cs, AccountsApi.sln, AccountsApi/AccountsApi.csproj, AccountsApi/V1/Domain/AccountSns.cs, AccountsApi/V1/Domain/User.cs, AccountsApi/V1/Gateways/AccountSnsGateway.cs, AccountsApi/V1/Gateways/ISnsGateway.cs, AccountsApi/V1/UseCase/GetAllUseCase.cs, AccountsApi/appsettings.json, AccountsApi/serverless.yml, Makefile, docker-compose.yml
https://app.clickup.com/t/1ck5krn
This PR adds the SQS and SNS infrastructure as well as the SNS gateway to allow create and update events to be published.
This will allow other dependent services to be notified when there are changes to account records.
- Added SNS accounts topic
- Added accounts queue
- Added accounts SNS gateway to publish create/update events
- Once the create and update use cases are completed and merged a line to call the SNS gateway will be added.
=> Add event notifications Infrastructure

AccountsApi.Tests/V1/Controllers/AccountsApiControllerTests.cs, AccountsApi.Tests/V1/Factories/EntityFactoryTest.cs, AccountsApi.Tests/V1/UseCase/AddUseCaseTests.cs, AccountsApi.Tests/V1/UseCase/GetAllUseCaseTests.cs, AccountsApi/V1/Factories/EntityFactory.cs
=> Unit testT verification inner procedures and some changes

AccountsApi.Tests/V1/Infrastructure/CorrelationMiddlewareTests.cs, AccountsApi/AccountsApi.csproj, AccountsApi/Startup.cs, AccountsApi/V1/Controllers/AccountApiController.cs, AccountsApi/V1/Controllers/BaseController.cs, AccountsApi/V1/Controllers/HealthCheckController.cs, AccountsApi/V1/CorrelationMiddleware.cs, AccountsApi/V1/ExceptionMiddleware.cs, AccountsApi/V1/Infrastructure/AccountContext.cs, AccountsApi/V1/Infrastructure/BaseErrorResponse.cs, AccountsApi/V1/Infrastructure/DynamoDbDateTimeConverter.cs, AccountsApi/V1/Infrastructure/DynamoDbInitilisationExtensions.cs, AccountsApi/V1/Infrastructure/ExceptionExtensions.cs, AccountsApi/V1/Infrastructure/ModelStateExtension.cs, AccountsApi/V1/Infrastructure/NonEmptyGuidAttribute.cs, AccountsApi/V1/Infrastructure/RequiredDateTimeAttribute.cs
[ticket (12.4) Api](https://app.clickup.com/t/1da3d6p)
due to large file changes this PR is one of the future series PR
this pull request for controller implementation 
these changes consist of controllers methods implementation
=> Controller implementation

AccountsApi.Tests/V1/Boundary/Request/AccountRequestTests.cs, AccountsApi.Tests/V1/Controllers/AccountsApiControllerTests.cs, AccountsApi.Tests/V1/Controllers/BaseControllerTests.cs, AccountsApi.Tests/V1/Controllers/HealthCheckControllerTests.cs, AccountsApi.Tests/V1/Domain/AccountTests.cs, AccountsApi.Tests/V1/E2ETests/DynamoDbAccountsIntegrationTests.cs, AccountsApi.Tests/V1/Factories/EntityFactoryTest.cs, AccountsApi.Tests/V1/Factories/ResponseFactoryTest.cs, AccountsApi.Tests/V1/Gateways/DynamoDbGatewayTests.cs, AccountsApi.Tests/V1/Helper/AssertExtensions.cs, AccountsApi.Tests/V1/Helper/Constants.cs, AccountsApi.Tests/V1/Helper/FackDataHelper.cs, AccountsApi.Tests/V1/Helper/RandomDateHelper.cs, AccountsApi.Tests/V1/Helper/RandomEnumHelper .cs, AccountsApi.Tests/V1/Helper/RandomNumberHelper.cs, AccountsApi.Tests/V1/Helper/RandomStringHelper.cs, AccountsApi.Tests/V1/Infrastructure/AccountDbEntityTests.cs, AccountsApi.Tests/V1/Infrastructure/AllowedValuesAttributeTests.cs, AccountsApi.Tests/V1/Infrastructure/CorrelationMiddlewareTests.cs, AccountsApi.Tests/V1/Infrastructure/DynamoDbInitilisationExtensionsTests.cs, AccountsApi.Tests/V1/Infrastructure/ExceptionExtensionsTests.cs, AccountsApi.Tests/V1/UseCase/AddUseCaseTests.cs, AccountsApi.Tests/V1/UseCase/DbHealthCheckUseCaseTests.cs, AccountsApi.Tests/V1/UseCase/GetAllArrearsUseCaseTests.cs, AccountsApi.Tests/V1/UseCase/GetAllUseCaseTests.cs, AccountsApi.Tests/V1/UseCase/GetByIdUseCaseTests.cs, AccountsApi.Tests/V1/UseCase/ThrowOpsErrorUsecaseTests.cs, AccountsApi.Tests/V1/UseCase/UpdateUseCaseTests.cs, AccountsApi/appsettings.json, AccountsApi/serverless.yml
[ticket (12.4) Api](https://app.clickup.com/t/1da3d6p)
due to large file changes this PR is one of the future series PR
this pull request for unit testing and integration testing finalization
these changes consist of  unit test of gateway, infrastructures, E2E, ...
=> Unit testing final

AccountsApi/serverless.yml
[https://app.clickup.com/t/1da3d6p](https://app.clickup.com/t/1da3d6p)
give access to query on index
some changes in server less file to get access to the AWS user to the GSI
=> Give access to the GSI in server less file

.circleci/config.yml, AccountsApi/Startup.cs, AccountsApi/serverless.yml
- Fix for SNS permissions
- The API is not able to interact with SNS
- Added line to configure AWS resources for dependency injection.
=> Aws sns fix

AccountsApi/serverless.yml
https://app.clickup.com/t/1f8y2yy
- This PR adds token based authentication to the API.  Previously authentication was done via API keys.  However, a more robust authentication solution has been developed and is being applied.
- removed api key configuration from serverless config file
- add custom authoriser to serverless config file.
- This API will need to be added to the list of APIs in the authenticator app.
=> Add token authentication

AccountsApi/serverless.yml
- Fixed the serverless config file.
This PR fixes the issue that prevents the deployment from completing successfully.
- Added the missing 'events' config value.
=> add missing config line

.circleci/config.yml
This PR fixes an issue with CircleCi causing the deployment step to fail.
- Deployment fails in CircleCI
- Removed redundant context assignment on deployment step.
=> Serverless config fix

terraform/development/dynamodb.tf, terraform/production/dynamodb.tf, terraform/staging/dynamodb.tf
Creating GSI in deployment, after any deployment the table will loos the GSI
- Deployment fails cerating global indices for the account table 
- Global index added in terraform file
=> GSI creating in terraform

CODEOWNERS
- Update the codeowners file
- This is to allow better management of code reviews/updates including any cross workstream contributions.
=>  Update codeowners

AccountsApi.Tests/V1/Boundary/Response/AccountModelTests.cs, AccountsApi.Tests/V1/Domain/AccountTests.cs, AccountsApi.Tests/V1/Helper/Constants.cs, AccountsApi.Tests/V1/Helper/FackDataHelper.cs, AccountsApi.Tests/V1/Infrastructure/AccountDbEntityTests.cs, AccountsApi/V1/Domain/Person.cs, AccountsApi/V1/Domain/PrimaryTenant.cs, AccountsApi/V1/Domain/Tenure.cs, AccountsApi/V1/Infrastructure/AccountDbEntity.cs, AccountsApi/V1/Infrastructure/QueryResponseExtension.cs, pull_request_template.md
[https://app.clickup.com/t/1fu94fy](https://app.clickup.com/t/1fu94fy)
person id added to the primary tenant subset
=> Adding person

AccountsApi.Tests/V1/Boundary/Request/AccountRequestTests.cs, AccountsApi.Tests/V1/Gateways/DynamoDbGatewayTests.cs, AccountsApi/V1/Boundary/BaseModel/AccountBaseModel.cs, AccountsApi/V1/Boundary/BaseModel/AccountResponseModel.cs, AccountsApi/V1/Factories/EntityFactory.cs, AccountsApi/V1/Infrastructure/DynamoDbDateTimeConverter.cs, CODEOWNERS
[https://app.clickup.com/t/1fmdr0c](https://app.clickup.com/t/1fmdr0c)
some bug fixed about unit testing
=> bug fixed in unit test about updating account

AccountsApi.Tests/V1/Controllers/AccountsApiControllerTests.cs, AccountsApi/V1/Boundary/BaseModel/AccountBaseModel.cs
=> Bug fixing

AccountsApi/Startup.cs, AccountsApi/V1/Factories/EntityFactory.cs, AccountsApi/V1/Factories/ResponseFactory.cs, AccountsApi/V1/Infrastructure/DynamoDbEnumConverter.cs
[https://app.clickup.com/t/1h26883](https://app.clickup.com/t/1h26883)
Some changes about Json string converter
=> changes about the json string converter

AccountsApi/serverless.yml
=> Remove LambdaSecurityGroup

AccountsApi/V1/Boundary/Response/APIResponse.cs, AccountsApi/V1/Controllers/AccountSearchController.cs, AccountsApi/V1/Gateways/AccountElasticSearchGateway.cs, AccountsApi/V1/Gateways/AccountSnsGateway.cs, AccountsApi/V1/Gateways/Interfaces/IAccountElasticSearchGateway.cs, AccountsApi/V1/UseCase/Interfaces/ISearchUseCase.cs, AccountsApi/V1/UseCase/SearchUseCase.cs, AccountsApi/serverless.yml
=> Elastic search

AccountsApi/serverless.yml
=> ELASTICSEARCH_DOMAIN_URL added to serverless configuration

AccountsApi.Tests/V1/Infrastructure/Helper/SearchElasticSearchHelperTests.cs, AccountsApi/serverless.yml
=> Elastic search unit testin

AccountsApi.Tests/V1/Boundary/Request/AccountRequestTests.cs, AccountsApi.Tests/V1/Boundary/Response/AccountModelTests.cs, AccountsApi.Tests/V1/Domain/AccountTests.cs, AccountsApi.Tests/V1/Infrastructure/AccountDbEntityTests.cs, AccountsApi/Properties/launchSettings.json, AccountsApi/V1/Boundary/BaseModel/AccountBaseModel.cs, AccountsApi/V1/Domain/Account.cs, AccountsApi/V1/Factories/EntityFactory.cs, AccountsApi/V1/Factories/ResponseFactory.cs, AccountsApi/V1/Infrastructure/AccountDbEntity.cs
=> End of reason field added

AccountsApi.Tests/V1/Helper/Constants.cs, AccountsApi/V1/Domain/Tenure.cs, AccountsApi/V1/Infrastructure/QueryResponseExtension.cs
=> Some bug fixed

.circleci/config.yml, AccountsApi.Tests/V1/Controllers/AccountsApiControllerTests.cs, AccountsApi.Tests/V1/Gateways/DynamoDbGatewayTests.cs, AccountsApi/Startup.cs, AccountsApi/V1/Controllers/AccountApiController.cs, AccountsApi/V1/Factories/EntityFactory.cs, AccountsApi/V1/Gateways/AccountApiGateway.cs, AccountsApi/V1/Gateways/DynamoDbGateway.cs, AccountsApi/V1/Gateways/Interfaces/IAccountApiGateway.cs, AccountsApi/V1/UseCase/AddBatchUseCase.cs, AccountsApi/V1/UseCase/Interfaces/IAddBatchUseCase.cs, AccountsApi/appsettings.Development.json, AccountsApi/appsettings.json
For data migration added Batch Insertion Endpoint
Added Batch Insertion Endpoint which will insert the data in a batch manner with configurable number of items per batch.
- [checked ] Added end-to-end (i.e. integration) tests where necessary e.g to test complete functionality of a newly added feature
- [checked  ] Added tests to cover all new production code
- [ checked ] Added comments to the README or updated relevant documentation _(add link to documentation)_, where necessary.
- …
=> Added Batch Insertion Endpoint

terraform/development/dynamodb.tf
=> read_capacity and write_capacity increased

terraform/development/dynamodb.tf
=> GSI Write capacity increased

terraform/development/dynamodb.tf
=> Write and read capacity configuration

terraform/development/dynamodb.tf
Write Capacity Increase
Write Capacity Increase
Write Capacity Increase
- [true ] Added end-to-end (i.e. integration) tests where necessary e.g to test complete functionality of a newly added feature
- [true  ] Added tests to cover all new production code
- [true  ] Added comments to the README or updated relevant documentation _(add link to documentation)_, where necessary.
- [true  ] Checked all code for possible refactoring
- [ true ] Code pipeline builds correctly
Are there any next steps that need to addressed after merging this PR? Add them …
=> Write Capacity Increase

AccountsApi/V1/Domain/Enum.cs
Added UH Enum values
Added UH Enum values
Added UH Enum values
- [true ] Added end-to-end (i.e. integration) tests where necessary e.g to test complete functionality of a newly added feature
- [true  ] Added tests to cover all new production code
- [true  ] Added comments to the README or updated relevant documentation _(add link to documentation)_, where necessary.
- [true  ] Checked all code for possible refactoring
- [true  ] Code pipeline builds correctly
=> Added UH Enum values

AccountsApi/AccountsApi.csproj, AccountsApi/Startup.cs
Added Google Group Authorization
Added Google Group Authorization
Added Google Group Authorization
- [true ] Added end-to-end (i.e. integration) tests where necessary e.g to test complete functionality of a newly added feature
- [true  ] Added tests to cover all new production code
- [true  ] Added comments to the README or updated relevant documentation _(add link to documentation)_, where necessary.
- [true  ] Checked all code for possible refactoring
- [true  ] Code pipeline builds correctly
Are there any next steps that need to addressed after …
=> Added Google Group Authorization

AccountsApi/Startup.cs, AccountsApi/V1/Controllers/AccountApiController.cs, AccountsApi/serverless.yml
Fixed Swagger Issue
Fixed Swagger Issue
Fixed Swagger Issue
- [ true] Added end-to-end (i.e. integration) tests where necessary e.g to test complete functionality of a newly added feature
- [true ] Added tests to cover all new production code
- [ true] Added comments to the README or updated relevant documentation _(add link to documentation)_, where necessary.
- [true ] Checked all code for possible refactoring
- [true ] Code pipeline builds correctly
=> Fixed Swagger Issue

AccountsApi/V1/Infrastructure/QueryResponseExtension.cs
=> Consolidated balance and end reason code were missed in factory

.circleci/config.yml
=> Remove deprecated account param

AccountsApi/serverless.yml
=> Remove account option from serverless config file

.circleci/config.yml
[https://app.clickup.com/t/21phgtm](https://app.clickup.com/t/21phgtm)
DynamoDb Auto scaling mode amendment due to massive records insertion in data migration
=> code format

.circleci/config.yml, terraform/development/dynamodb.tf, terraform/production/dynamodb.tf, terraform/staging/dynamodb.tf
=> Dynamodb auto scaling mode

.circleci/config.yml, AccountsApi/serverless.yml
Add npm package to ci config
introduce waf plugin to serverless
=> Changes to yml to enable WAF

.circleci/config.yml, terraform/development/dynamodb.tf, terraform/development/terraform-compliance/dynamodb.feature, terraform/development/terraform-compliance/sns.feature, terraform/production/terraform-compliance/dynamodb.feature, terraform/production/terraform-compliance/sns.feature, terraform/staging/dynamodb.tf, terraform/staging/terraform-compliance/dynamodb.feature, terraform/staging/terraform-compliance/sns.feature
Changes to circle-ci/config.yml
dynamodb and sns feature files added to dev, staging and prod terraform
https://hackney.atlassian.net/browse/HFS-442
Applying Terraform-Compliance to the Accounts API.
- Changes to the Circle-CI config file
- Addition of BDD feature files for DynamoDb and SNS to each of the environment terraform folders
- Tweaks to the dynamodb.tf file to conform to the feature files
=> Apply Terraform Compliance

terraform/development/terraform-compliance/dynamodb.feature
Reapplying the scenarios that were removed!!
=> update the dynamodb feature file

terraform/development/terraform-compliance/dynamodb.feature, terraform/staging/dynamodb.tf
=> account-api development > master Merge 

.circleci/config.yml, AccountsApi.Tests/AccountsApi.Tests.csproj, AccountsApi.Tests/Dockerfile, AccountsApi/AccountsApi.csproj, AccountsApi/Dockerfile, AccountsApi/Startup.cs, AccountsApi/build.cmd, AccountsApi/build.sh, AccountsApi/serverless.yml, terraform/staging/dynamodb.tf
- A merge of #96 from development to master.
- A consequence of branching strategy.
- The changes were already tested on development environment.
=> Merge of #96 to master.

.circleci/config.yml, AccountsApi.Tests/AccountsApi.Tests.csproj, AccountsApi.Tests/Dockerfile, AccountsApi/AccountsApi.csproj, AccountsApi/Dockerfile, AccountsApi/Startup.cs, AccountsApi/build.cmd, AccountsApi/build.sh, AccountsApi/serverless.yml
=> Revert the upgrade

AccountsApi/AccountsApi.csproj, AccountsApi/Startup.cs, terraform/production/dynamodb.tf
- A merge of the #101 from `development` to `master` branch.
- A consequence of the branching strategy.
=> Merge of #101 to master.

AccountsApi.Tests/V1/Gateways/DynamoDbGatewayTests.cs, AccountsApi/V1/Gateways/AccountApiGateway.cs, AccountsApi/V1/Gateways/DynamoDbGateway.cs
Fix logging messages to print account ID so that they're more useful for debugging
=> Update logging messages for account ID

AccountsApi.Tests/V1/Gateways/DynamoDbGatewayTests.cs, AccountsApi/V1/Gateways/AccountApiGateway.cs, AccountsApi/V1/Gateways/DynamoDbGateway.cs, AccountsApi/V1/UseCase/AddBatchUseCase.cs, AccountsApi/V1/UseCase/AddUseCase.cs, AccountsApi/V1/UseCase/GetAllArrearsUseCase.cs, AccountsApi/V1/UseCase/GetAllUseCase.cs, AccountsApi/V1/UseCase/GetByIdUseCase.cs, AccountsApi/V1/UseCase/UpdateUseCase.cs
Set logging level of all logs to information so that they are visible in staging and prod environments
=> Update logging level

AccountsApi.Tests/V1/Gateways/DynamoDbGatewayTests.cs, AccountsApi/V1/Gateways/AccountApiGateway.cs, AccountsApi/V1/Gateways/DynamoDbGateway.cs, AccountsApi/V1/UseCase/AddBatchUseCase.cs, AccountsApi/V1/UseCase/AddUseCase.cs, AccountsApi/V1/UseCase/GetAllArrearsUseCase.cs, AccountsApi/V1/UseCase/GetAllUseCase.cs, AccountsApi/V1/UseCase/GetByIdUseCase.cs, AccountsApi/V1/UseCase/UpdateUseCase.cs
Deploy #109 to staging and production.
=> Deploy logging changes

AccountsApi.Tests/AccountsApi.Tests.csproj, AccountsApi.Tests/Dockerfile, AccountsApi.Tests/V1/Controllers/AccountsApiControllerTests.cs, AccountsApi.Tests/V1/Controllers/BaseControllerTests.cs, AccountsApi.Tests/V1/Infrastructure/AllowedValuesAttributeTests.cs, AccountsApi.Tests/V1/Infrastructure/CorrelationMiddlewareTests.cs, AccountsApi.Tests/V1/UseCase/AddUseCaseTests.cs, AccountsApi/AccountsApi.csproj, AccountsApi/Dockerfile, AccountsApi/V1/Boundary/BaseModel/AccountBaseModel.cs, AccountsApi/V1/Boundary/Request/ArrearRequest.cs, AccountsApi/build.cmd, AccountsApi/build.sh, AccountsApi/serverless.yml
Ticket [HPT-583](https://hackney.atlassian.net/browse/HPT-583)
Upgrade to .NET 8.0
[HPT-583]: https://hackney.atlassian.net/browse/HPT-583?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> .NET 8 upgrade

AccountsApi/V1/Boundary/BaseModel/AccountBaseModel.cs
Currently there's a bug due to the wrong namespace specified for AllowedValues - should be `AccountsApi.V1.Infrastructure`
=> Fix allowed values

AccountsApi/V1/Boundary/BaseModel/AccountBaseModel.cs, CODEOWNERS
=> Release fix allowed values

AccountsApi/serverless.yml
Update dev and staging lambda authorizer
- Hardcode authorizer ARNs in serverless, preventing any unintended changes via parameter store
- Update dev/staging authorizer to the new version
=> Update non prod authorizer

AccountsApi/serverless.yml
Updated production authorizer ARN
=> Update production authorizer ARN
